---
Serilog:
  Using:
  - Serilog.Sinks.Console
  - Serilog.Sinks.File
  MinimumLevel:
    Default: "Information"
    Override:
      Microsoft: Information
      System: Information
  Enrich:
  - FromLogContext
  - WithMachineName
  - WithProcessId
  - WithThreadId
  WriteTo:
  - Name: Console
  - Name: File
    Args:
      path: "%LOG_FOLDER%/log.log"
      rollingInterval: Day
      outputTemplate: "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {CorrelationId} {Level:u3}] {Username} {Message:lj}{NewLine}{Exception}"
AllowedHosts: "*"
AppConfiguration:
  TMDB_API_KEY: {{ TMDB API KEY}}
  TAG_NAME: "q" # must be the same as the tag name in indexers
  WATCH_PROVIDERS: "FR:Netflix,US:Amazon Prime Video" # format: REGION:PROVIDER,REGION:PROVIDER
  Clients: # one or more clients
    - ApiKey: {{ SONARR_OR_RADARR_API_KEY }}
      BaseUrl: "https://radarr.com"
    - ApiKey: {{ SONARR_OR_RADARR_API_KEY }}
      BaseUrl: "https://sonarr.com"